name: Edge Automated Build with .Net Core

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Build:

    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v5
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Replace tokens
      uses: cschleiden/replace-tokens@v1
      with:
        files: '["**/*.json"]'
      env:
        browser: Edge
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        path: |
              JupiterCloud/Logs*
        if-no-files-found: warn
